name: Deploy to Cloud Run

on:
  push:
    branches: [main]  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: willbigquery
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Build and Push Docker image to GCR
      run: |
        gcloud builds submit . --tag gcr.io/willbigquery/financial-news-ml

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy financial-sentiment \
          --image gcr.io/willbigquery/financial-news-ml \
          --platform managed \
          --region northamerica-northeast1 \
          --allow-unauthenticated
