name: Deploy to Cloud Run
on:
  push:
    branches: [main]  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Configure Docker for GCR
      run: gcloud auth configure-docker
    
    - name: Build and Push Docker image
      run: |
        echo "Building Docker image..."
        docker build -t gcr.io/willbigquery/financial-news-ml .
        echo "Pushing Docker image to GCR..."
        docker push gcr.io/willbigquery/financial-news-ml
        echo "Docker image pushed successfully!"
    
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy financial-sentiment \
          --image gcr.io/willbigquery/financial-news-ml \
          --platform managed \
          --region northamerica-northeast1 \
          --allow-unauthenticated
